project:
  type: website

website:
  title: "qmd-github-project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: bharat-market-pulse-learnings.qmd
        text: Bharat Market Pulse

format:
  html:
    theme: cosmo
    toc: true
